export interface Game {
  id: string
  name: string
  genre: string
  price: number // per hour in MNT
  players: string
  description: string
  color: string // neon accent
  icon: string // emoji-free, just a short code label
  tag?: string
}

export interface EsportsCenter {
  id: string
  name: string
  district: string
  address: string
  phone: string
  pcCount: number
  pricePerHour: number
  rating: number
  reviewCount: number
  openHours: string
  amenities: string[]
  // grid position (percent x, y)
  x: number
  y: number
  color: string
}

export interface Review {
  centerId: string
  userName: string
  rating: number
  comment: string
  date: string
}

export const GAMES: Game[] = [
  {
    id: 'cs2',
    name: 'Counter-Strike 2',
    genre: 'FPS',
    price: 3000,
    players: '5v5',
    description: 'Дэлхийн хамгийн алдартай tactical shooter. CT vs T командууд.',
    color: '#f97316',
    icon: 'CS2',
    tag: 'TOP',
  },
  {
    id: 'valorant',
    name: 'Valorant',
    genre: 'Tactical FPS',
    price: 3000,
    players: '5v5',
    description: 'Riot Games-ийн tactical shooter. Unique agent abilities.',
    color: '#ff2d78',
    icon: 'VAL',
    tag: 'HOT',
  },
  {
    id: 'dota2',
    name: 'Dota 2',
    genre: 'MOBA',
    price: 2500,
    players: '5v5',
    description: 'Valve-ийн MOBA тоглоом. 120+ hero, гүнзгий strategy.',
    color: '#c026d3',
    icon: 'D2',
  },
  {
    id: 'lol',
    name: 'League of Legends',
    genre: 'MOBA',
    price: 2500,
    players: '5v5',
    description: 'Дэлхийн хамгийн их тоглогддог MOBA тоглоом.',
    color: '#00d4ff',
    icon: 'LoL',
  },
  {
    id: 'pubg',
    name: 'PUBG: Battlegrounds',
    genre: 'Battle Royale',
    price: 3500,
    players: '1-4',
    description: '100 тоглогч battle royale. Реалист график, тактик тоглолт.',
    color: '#eab308',
    icon: 'PBG',
    tag: 'NEW',
  },
  {
    id: 'fc25',
    name: 'EA Sports FC 25',
    genre: 'Sports',
    price: 2000,
    players: '1v1',
    description: 'Хөлбөмбөгийн симулятор. Ultimate Team, Career режимүүд.',
    color: '#22c55e',
    icon: 'FC25',
  },
  {
    id: 'apex',
    name: 'Apex Legends',
    genre: 'Battle Royale FPS',
    price: 3000,
    players: '3v3',
    description: 'EA-ийн fast-paced battle royale. Legend abilities.',
    color: '#ef4444',
    icon: 'APX',
  },
  {
    id: 'ow2',
    name: 'Overwatch 2',
    genre: 'Hero Shooter',
    price: 2500,
    players: '5v5',
    description: 'Blizzard-ийн hero shooter. Tank, DPS, Support.',
    color: '#f97316',
    icon: 'OW2',
  },
  {
    id: 'r6s',
    name: 'Rainbow Six Siege',
    genre: 'Tactical FPS',
    price: 3500,
    players: '5v5',
    description: 'Ubisoft-ийн tactical shooter. Operator abilities, destructible env.',
    color: '#00d4ff',
    icon: 'R6S',
  },
  {
    id: 'genshin',
    name: 'Genshin Impact',
    genre: 'Action RPG',
    price: 2000,
    players: '1-4',
    description: 'Open world action RPG. Teyvat дэлхийд аялах.',
    color: '#a855f7',
    icon: 'GEN',
  },
  {
    id: 'wow',
    name: 'World of Warcraft',
    genre: 'MMORPG',
    price: 2500,
    players: 'MMO',
    description: 'Blizzard-ийн legendary MMORPG. Raid, dungeon, PvP.',
    color: '#f59e0b',
    icon: 'WoW',
  },
  {
    id: 'fortnite',
    name: 'Fortnite',
    genre: 'Battle Royale',
    price: 2500,
    players: '1-4',
    description: 'Epic-ийн battle royale. Building mechanics, seasonial events.',
    color: '#8b5cf6',
    icon: 'FTN',
    tag: 'HOT',
  },
  {
    id: 'minecraft',
    name: 'Minecraft',
    genre: 'Sandbox',
    price: 2000,
    players: '1-8',
    description: 'Дэлхийн хамгийн их зарагдсан тоглоом. Build, survive, explore.',
    color: '#84cc16',
    icon: 'MC',
  },
  {
    id: 'gta5',
    name: 'GTA V Online',
    genre: 'Open World',
    price: 3000,
    players: '1-30',
    description: 'Rockstar-ийн open world action. Los Santos-д чөлөөтэй тоглох.',
    color: '#14b8a6',
    icon: 'GTA',
  },
  {
    id: 'rocketleague',
    name: 'Rocket League',
    genre: 'Sports',
    price: 2000,
    players: '3v3',
    description: 'Машинтай хөлбөмбөг. Unique mechanics, competitive esports.',
    color: '#06b6d4',
    icon: 'RL',
  },
  {
    id: 'deadlock',
    name: 'Deadlock',
    genre: 'Hero Shooter MOBA',
    price: 3500,
    players: '6v6',
    description: 'Valve-ийн шинэ MOBA shooter hybrid. Early access.',
    color: '#ff2d78',
    icon: 'DLK',
    tag: 'NEW',
  },
  {
    id: 'starcraft2',
    name: 'StarCraft II',
    genre: 'RTS',
    price: 2000,
    players: '1v1',
    description: 'Blizzard-ийн legendary RTS. Pro scene-д хамгийн хүчтэй нэг.',
    color: '#3b82f6',
    icon: 'SC2',
  },
  {
    id: 'tekken8',
    name: 'Tekken 8',
    genre: 'Fighting',
    price: 2500,
    players: '1v1',
    description: 'Namco-ийн 3D fighting game. 32 character roster.',
    color: '#ef4444',
    icon: 'T8',
    tag: 'NEW',
  },
  {
    id: 'eldenring',
    name: 'Elden Ring',
    genre: 'Action RPG',
    price: 3000,
    players: '1-3',
    description: 'FromSoftware-ийн masterpiece. Open world soulslike.',
    color: '#d4a017',
    icon: 'ER',
  },
  {
    id: 'lethal',
    name: 'Lethal Company',
    genre: 'Horror Co-op',
    price: 2500,
    players: '1-4',
    description: 'Indie co-op horror. Хамт найзуудтайгаа monster-аас дүүрэх.',
    color: '#22c55e',
    icon: 'LC',
    tag: 'HOT',
  },
]

export const CENTERS: EsportsCenter[] = [
  {
    id: 'c1',
    name: 'CyberArena UB',
    district: 'Сүхбаатар',
    address: 'Сүхбаатар дүүрэг, 1-р хороо, Чингисийн өргөн чөлөө 12',
    phone: '7711-0001',
    pcCount: 60,
    pricePerHour: 3000,
    rating: 4.8,
    reviewCount: 142,
    openHours: '09:00 — 02:00',
    amenities: ['RTX 4090', '240Hz Monitor', 'Headset', 'Food & Drink'],
    x: 52,
    y: 38,
    color: '#00d4ff',
  },
  {
    id: 'c2',
    name: 'NeonZone Gaming',
    district: 'Баянзүрх',
    address: 'Баянзүрх дүүрэг, 4-р хороо, Нарны зам 55',
    phone: '7711-0002',
    pcCount: 40,
    pricePerHour: 2500,
    rating: 4.6,
    reviewCount: 98,
    openHours: '10:00 — 00:00',
    amenities: ['RTX 4080', '165Hz Monitor', 'Locker'],
    x: 68,
    y: 52,
    color: '#ff2d78',
  },
  {
    id: 'c3',
    name: 'ProGamer Hub',
    district: 'Баянгол',
    address: 'Баянгол дүүрэг, 6-р хороо, Энхтайвны өргөн чөлөө 23',
    phone: '7711-0003',
    pcCount: 50,
    pricePerHour: 2800,
    rating: 4.7,
    reviewCount: 115,
    openHours: '08:00 — 02:00',
    amenities: ['RTX 4090', '360Hz Monitor', 'VR Room', 'Snack Bar'],
    x: 35,
    y: 60,
    color: '#00d4ff',
  },
  {
    id: 'c4',
    name: 'Pixel Palace',
    district: 'Хан-Уул',
    address: 'Хан-Уул дүүрэг, 11-р хороо, Зайсан гудамж 8',
    phone: '7711-0004',
    pcCount: 30,
    pricePerHour: 2000,
    rating: 4.4,
    reviewCount: 67,
    openHours: '11:00 — 23:00',
    amenities: ['RTX 3080', '144Hz Monitor'],
    x: 42,
    y: 72,
    color: '#a855f7',
  },
  {
    id: 'c5',
    name: 'StarLAN Center',
    district: 'Чингэлтэй',
    address: 'Чингэлтэй дүүрэг, 2-р хороо, Их Тойруу 14',
    phone: '7711-0005',
    pcCount: 45,
    pricePerHour: 2500,
    rating: 4.5,
    reviewCount: 88,
    openHours: '10:00 — 01:00',
    amenities: ['RTX 4070', '240Hz Monitor', 'PS5 Zone'],
    x: 58,
    y: 28,
    color: '#00d4ff',
  },
  {
    id: 'c6',
    name: 'GalacticLAN',
    district: 'Сонгинохайрхан',
    address: 'Сонгинохайрхан дүүрэг, 8-р хороо, Шинэ хотхон 3',
    phone: '7711-0006',
    pcCount: 35,
    pricePerHour: 2200,
    rating: 4.3,
    reviewCount: 54,
    openHours: '10:00 — 00:00',
    amenities: ['RTX 4070', '165Hz Monitor', 'Locker'],
    x: 22,
    y: 44,
    color: '#22c55e',
  },
  {
    id: 'c7',
    name: 'Thunder Esports',
    district: 'Баянзүрх',
    address: 'Баянзүрх дүүрэг, 14-р хороо, Хүннү гудамж 7',
    phone: '7711-0007',
    pcCount: 55,
    pricePerHour: 3500,
    rating: 4.9,
    reviewCount: 203,
    openHours: '09:00 — 03:00',
    amenities: ['RTX 4090 Ti', '360Hz Monitor', 'Pro Training Room', 'Canteen'],
    x: 75,
    y: 40,
    color: '#ff2d78',
  },
  {
    id: 'c8',
    name: 'QuantumPlay',
    district: 'Налайх',
    address: 'Налайх дүүрэг, 1-р хороо, Наадмын талбай 2',
    phone: '7711-0008',
    pcCount: 25,
    pricePerHour: 1800,
    rating: 4.2,
    reviewCount: 41,
    openHours: '11:00 — 22:00',
    amenities: ['RTX 3070', '144Hz Monitor'],
    x: 88,
    y: 65,
    color: '#eab308',
  },
  {
    id: 'c9',
    name: 'BladeRunner GG',
    district: 'Багахангай',
    address: 'Баянгол дүүрэг, 3-р хороо, Ажлын хэрэгт 21',
    phone: '7711-0009',
    pcCount: 38,
    pricePerHour: 2600,
    rating: 4.6,
    reviewCount: 79,
    openHours: '10:00 — 01:00',
    amenities: ['RTX 4080', '240Hz Monitor', 'Streaming Station'],
    x: 30,
    y: 30,
    color: '#00d4ff',
  },
  {
    id: 'c10',
    name: 'NovaLAN Pro',
    district: 'Хан-Уул',
    address: 'Хан-Уул дүүрэг, 5-р хороо, Зайсан хороолол 19',
    phone: '7711-0010',
    pcCount: 48,
    pricePerHour: 3200,
    rating: 4.7,
    reviewCount: 126,
    openHours: '09:00 — 02:00',
    amenities: ['RTX 4090', '360Hz Monitor', 'VIP Room', 'Café'],
    x: 48,
    y: 82,
    color: '#ff2d78',
  },
]
